name = "Faiss"
uuid = "97d83715-92a6-43f6-a1c3-b293f6dd920a"
authors = ["zhangyong <github.com/zsz00>", "Christopher Doris <github.com/cjdoris>"]
version = "0.3.5"

[deps]
CEnum = "fa961155-64e5-5f13-b03f-caf6b980ea82"
Faiss_jll = "d7fe3460-1609-53b1-864c-4d331a5b7338"

[compat]
CEnum = "0.5.0"
Faiss_jll = "1.9.0"
julia = "1.6"
